CREATE OR REPLACE TABLE SYMETRICAL_DLR(
    FSCL_YR_NB NUMBER AS FSCL_YR_NB,
    MNTH_NB NUMBER AS FSCL_MNTH_NB,
    DLR_CD VARCHAR(4) AS DLR_CD,
    AREA VARCHAR(55) AS ARA_IN_NM,
    INDICATOR VARCHAR(55) AS IN_NM,
    SIGN VARCHAR(1) AS SGN_IN_DS,
    NUMERATOR NUMBER(12,2) AS NMRTR_MSR_NB,
    DENOMINATOR NUMBER(12,2) AS DNMNTR_MSR_NB,
    ACTUAL NUMBER(12,2) AS ACTL_CMPLNC_NB,
    TARGET NUMBER(12,2) AS IN_OBJCTV_NB,
    CDO_PERCENTAGE NUMBER(12,6) AS CMPLNC_OF_OBJCTV_PC);
    
GRANT SELECT, INSERT, UPDATE, REFERENCES ON SDDBMTS1.NMX_MTS1_STG.SYMETRICAL_DLR TO ROLE "ENTER ROLE"_$(ENV);