CREATE OR REPLACE TABLE SYMETRICAL_DLR(
    FSCL_YR_NB INT,
    MNTH_NB INT,
    DLR_CD INT,
    AREA STRING,
    INDICATOR STRING,
    SIGN STRING,
    NUMERATOR DOUBLE,
    DENOMINATOR DOUBLE,
    ACTUAL DOUBLE,
    TARGET DOUBLE,
    CDO_PERCENTAGE DOUBLE,
    HashKey STRING,              
    audit_loaded_date TIMESTAMP );
    
GRANT SELECT, INSERT, UPDATE, REFERENCES ON SDDBMTS1.NMX_MTS1_STG.SYMETRICAL_DLR TO ROLE "ENTER ROLE"_$(ENV);