

CREATE OR REPLACE TEMPORARY TABLE 
S3_TO_SNOWFLAKE.PUBLIC.TRANSFORMER 

AS
(
SELECT 
    CAST(HASHKEY AS STRING) AS SLS_CMPLNC_OF_OBJCTV_KY,
    CASE
        WHEN
            LEN(FSCL_MNTH_NB)=1 
            THEN
                CONCAT('0',FSCL_YR_NB,'0', FSCL_MNTH_NB, '01') 
        WHEN
            LEN(FSCL_MNTH_NB)>1 
            THEN
            CONCAT('0',FSCL_YR_NB, FSCL_MNTH_NB, '01')
            ELSE NULL
            END AS CLNDR_DT,
    LPAD(DLR_CD, 4, '0') AS DLR_KY, 
    LPAD(DLR_CD, 4, '0') AS DLR_CD,
    CMPLNC_OF_OBJCTV_PC,
    AUDIT_LOADED_DATE AS ADT_LOD_DT
    
 FROM S3_TO_SNOWFLAKE.PUBLIC.SLS_CMPLNC_OF_OBJCTV_SG 
WHERE DATE(ADT_LOD_DT) > DATEADD(MONTH, -1, CURRENT_DATE())
    
    );


MERGE INTO S3_TO_SNOWFLAKE.PUBLIC.SLS_CMPLNC_OF_OBJCTV_2_SG AS target
USING 
S3_TO_SNOWFLAKE.PUBLIC.TRANSFORMER AS source
ON target.SLS_CMPLNC_OF_OBJCTV_KY = source.SLS_CMPLNC_OF_OBJCTV_KY  
-- Condición de coincidencia en la clave primaria
WHEN MATCHED 
THEN     
UPDATE 
SET   
    TARGET.CLNDR_DT = SOURCE.CLNDR_DT ,
    TARGET.DLR_KY = SOURCE.DLR_KY,
    TARGET.DLR_CD = SOURCE.DLR_CD,
    TARGET.CMPLNC_OF_OBJCTV_PC = SOURCE.CMPLNC_OF_OBJCTV_PC,
    TARGET.ADT_LOD_DT = SOURCE.ADT_LOD_DT,
    --TARGET.CRTE_USR_ID = SOURCE.CRTE_USR_ID,
    TARGET.UPDT_USR_ID = CURRENT_USER ,
    --TARGET.CRTE_TS = SOURCE.CRTE_TS ,
    TARGET.UPDT_TS  = GETDATE()
       
WHEN NOT MATCHED 
THEN     
INSERT 
    (
        SLS_CMPLNC_OF_OBJCTV_KY, 
        CLNDR_DT, 
        DLR_KY, 
        DLR_CD, 
        CMPLNC_OF_OBJCTV_PC, 
        ADT_LOD_DT, 
        CRTE_USR_ID, 
        UPDT_USR_ID, 
        CRTE_TS, 
        UPDT_TS
        
    )    
VALUES 
    (
        SOURCE.SLS_CMPLNC_OF_OBJCTV_KY,
        SOURCE.CLNDR_DT ,
        SOURCE.DLR_KY,
        SOURCE.DLR_CD,
        SOURCE.CMPLNC_OF_OBJCTV_PC,
        SOURCE.ADT_LOD_DT,
        CURRENT_USER,
        CURRENT_USER ,
        GETDATE() ,
        GETDATE()
    );




