CREATE OR REPLACE TABLE NRFM (
    FSCL_YR_NB NUMBER AS FSCL_YR_NB,
    MNTH_NB NUMBER AS FSCL_MNTH_NB,
    DLR_CD VARCHAR(4) AS DLR_CD,
    DEALER VARCHAR(55) AS DLR_NM,
    REGION VARCHAR(55) AS RGNL_ZN_NM,
    ZONE_MANAGER VARCHAR(55) AS DLR_ACNT_MGR_NM,
    "GROUP" VARCHAR(55) AS DLR_GRP_NM,
    CONTRACTS_TARGET NUMBER(12,2) AS CNTRCT_TRGT_NB,
    RETAIL_CONTRACTS NUMBER(12,2) AS RTL_CNTRCT_NB,
    RETAIL_SALES_NMEX NUMBER(12,2) AS RTL_SL_NMEX_NB,
    SELECTIVITY_LEASING NUMBER(12,2) AS SELECTIVITY_LEASING_NB,
    EXTENDED_WARRANTY_PERCENTAGE NUMBER(12,6) AS EXTND_WRNTY_PC,
    HashKey STRING,              
    audit_loaded_date TIMESTAMP  
);

GRANT SELECT, INSERT, UPDATE, REFERENCES ON SDDBMTS1.NMX_MTS1_STG.NRFM TO ROLE "ENTER ROLE"_$(ENV);