CREATE OR REPLACE TABLE ICON_AVG_ORS_MENSUAL (
    FSCL_YR_NB NUMBER AS FSCL_YR_NB,
    DLR_CD VARCHAR(4) AS DLR_CD,
    DSTRBR VARCHAR(150) AS DLR_NM,
    "GROUP" VARCHAR(55) AS DLR_GRP_NM,
    APRIL_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_1_ORDR_PBLC_WRNTY_INTRNL_NB,
    MAY_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_2_ORDR_PBLC_WRNTY_INTRNL_NB,
    JUNE_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_3_ORDR_PBLC_WRNTY_INTRNL_NB,
    JULY_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_4_ORDR_PBLC_WRNTY_INTRNL_NB,
    AUGUST_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_5_ORDR_PBLC_WRNTY_INTRNL_NB,
    SEPTEMBER_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_6_ORDR_PBLC_WRNTY_INTRNL_NB,
    OCTOBER_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_7_ORDR_PBLC_WRNTY_INTRNL_NB,
    NOVEMBER_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_8_ORDR_PBLC_WRNTY_INTRNL_NB,
    DECEMBER_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_9_ORDR_PBLC_WRNTY_INTRNL_NB,
    JANUARY_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_10_ORDR_PBLC_WRNTY_INTRNL_NB,
    FEBRUARY_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_11_ORDR_PBLC_WRNTY_INTRNL_NB,
    MARCH_ORDERS_PUB_GAR_INT NUMBER(12,2) AS VLU_12_ORDR_PBLC_WRNTY_INTRNL_NB,
    APRIL_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_1_ORDR_PBLC_WRNTY_NB,
    MAY_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_2_ORDR_PBLC_WRNTY_NB,
    JUNE_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_3_ORDR_PBLC_WRNTY_NB,
    JULY_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_4_ORDR_PBLC_WRNTY_NB,
    AUGUST_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_5_ORDR_PBLC_WRNTY_NB,
    SEPTEMBER_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_6_ORDR_PBLC_WRNTY_NB,
    OCTOBER_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_7_ORDR_PBLC_WRNTY_NB,
    NOVEMBER_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_8_ORDR_PBLC_WRNTY_NB,
    DECEMBER_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_9_ORDR_PBLC_WRNTY_NB,
    JANUARY_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_10_ORDR_PBLC_WRNTY_NB,
    FEBRUARY_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_11_ORDR_PBLC_WRNTY_NB,
    MARCH_ORDERS_PUB_GAR NUMBER(12,2) AS VLU_12_ORDR_PBLC_WRNTY_NB,
    HashKey STRING,              -- Added column for unique row identifier or hash
    audit_loaded_date TIMESTAMP  -- Added column for tracking when the row was loaded
);

GRANT SELECT, INSERT, UPDATE, REFERENCES ON SDDBMTS1.NMX_MTS1_STG.ICON_AVG_ORS_MENSUAL TO ROLE "ENTER ROLE"_$(ENV);