CREATE OR REPLACE TABLE ICON_AVG_ORS_MENSUAL (
    FSCL_YR_NB INT,
    DLR_CD INT,
    DSTRBR STRING,
    GROUP STRING,
    APRIL_ORDERS_PUB_GAR_INT INT,
    MAY_ORDERS_PUB_GAR_INT INT,
    JUNE_ORDERS_PUB_GAR_INT INT,
    JULY_ORDERS_PUB_GAR_INT INT,
    AUGUST_ORDERS_PUB_GAR_INT INT,
    SEPTEMBER_ORDERS_PUB_GAR_INT INT,
    OCTOBER_ORDERS_PUB_GAR_INT INT,
    NOVEMBER_ORDERS_PUB_GAR_INT INT,
    DECEMBER_ORDERS_PUB_GAR_INT INT,
    JANUARY_ORDERS_PUB_GAR_INT INT,
    FEBRUARY_ORDERS_PUB_GAR_INT INT,
    MARCH_ORDERS_PUB_GAR_INT INT,
    APRIL_ORDERS_PUB_GAR INT,
    MAY_ORDERS_PUB_GAR INT,
    JUNE_ORDERS_PUB_GAR INT,
    JULY_ORDERS_PUB_GAR INT,
    AUGUST_ORDERS_PUB_GAR INT,
    SEPTEMBER_ORDERS_PUB_GAR INT,
    OCTOBER_ORDERS_PUB_GAR INT,
    NOVEMBER_ORDERS_PUB_GAR INT,
    DECEMBER_ORDERS_PUB_GAR INT,
    JANUARY_ORDERS_PUB_GAR INT,
    FEBRUARY_ORDERS_PUB_GAR INT,
    MARCH_ORDERS_PUB_GAR INT,
    HashKey STRING,              -- Added column for unique row identifier or hash
    audit_loaded_date TIMESTAMP  -- Added column for tracking when the row was loaded
);

GRANT SELECT, INSERT, UPDATE, REFERENCES ON SDDBMTS1.NMX_MTS1_STG.ICON_AVG_ORS_MENSUAL TO ROLE "ENTER ROLE"_$(ENV);