CREATE OR REPLACE TABLE CDO_DESGLOSE_TOTAL (
    FSCL_YR_NB NUMBER AS FSCL_YR_NB,
    FSCL_MNTH_NB NUMBER AS FSCL_MNTH_NB,
    "GROUP" VARCHAR(55) AS DLR_GRP_NM,
    DLR_CD VARCHAR(4) AS DLR_CD,
    DSTRBR VARCHAR(150) AS DLR_NM,
    OWNER VARCHAR(150) AS DLR_OWNR_NM,
    CDO NUMBER(12,6) AS CMPLNC_OF_OBJCTV_PC,
    HashKey STRING,             
    audit_loaded_date TIMESTAMP  
);
GRANT SELECT, INSERT, UPDATE, REFERENCES ON SDDBMTS1.NMX_MTS1_STG.CDO_DESGLOSE_TOTAL TO ROLE "ENTER ROLE"_$(ENV);