CREATE OR REPLACE TABLE CDO_DESGLOSE_TOTAL (
    FSCL_YR_NB INT,
    MNTH_NB INT,
    "GROUP" STRING,
    DLR_CD INT,
    DSTRBR STRING,
    OWNER STRING,
    CDO STRING,
    HashKey STRING,             
    audit_loaded_date TIMESTAMP  
);
GRANT SELECT, INSERT, UPDATE, REFERENCES ON SDDBMTS1.NMX_MTS1_STG.CDO_DESGLOSE_TOTAL TO ROLE "ENTER ROLE"_$(ENV);