CREATE OR REPLACE TABLE ICON_DEALERS (
    DLR_CD VARCHAR(4) AS DLR_CD,
    DSTRBR VARCHAR(150) AS DLR_NM,
    "GROUP" VARCHAR(55) AS DLR_GRP_NM,
    ZONE VARCHAR(55) AS DLR_ZN_NM,
    SALES VARCHAR(50) AS SLS_DS,
    AFTER_SALES VARCHAR(50) AS AFTR_SLS_DS,
    PREOWNED VARCHAR(50) AS POWN_DS,
    FLEETS VARCHAR(50) AS FLT_DS,
    MANAGERIAL VARCHAR(50) AS MGMT_BSNS_ARA_DS,
    HYP VARCHAR(50) AS SHT_MTL_PAINTING_BSNS_DS,
    WHOLESALE VARCHAR(50) AS WHLSL_DS,
    FOM VARCHAR(55) AS FOM_NM,
    DOM VARCHAR(55) AS DOM_NM,
    HashKey STRING,              -- Added column for unique row identifier or hash
    audit_loaded_date TIMESTAMP  -- Added column for tracking when the row was loaded
);

GRANT SELECT, INSERT, UPDATE, REFERENCES ON SDDBMTS1.NMX_MTS1_STG.ICON_DEALERS TO ROLE "ENTER ROLE"_$(ENV);