CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.IN_CMPLNC_NRFM_SG_PIPE 
AUTO_INGEST = TRUE 
AS COPY INTO SDDBMTS1.NMX_MTS1_STG.IN_CMPLNC_NRFM_SG (
    FSCL_YR_NB,
    FSCL_MNTH_NB,
    DLR_CD,
    DLR_NM,
    RGNL_ZN_NM,
    DLR_ACNT_MGR_NM,
    DLR_GRP_NM,
    CNTRCT_TRGT_NB,
    RTL_CNTRCT_NB,
    RTL_SL_NMEX_NB,
    SELECTIVITY_LEASING_NB,
    EXTND_WRNTY_PC,
    HASHKEY,
    AUDIT_LOADED_DATE
) FROM (
    SELECT
        $1::NUMBER AS FSCL_YR_NB,
        $2::NUMBER AS FSCL_MNTH_NB,
        $3::VARCHAR(4) AS DLR_CD,
        $4::VARCHAR(55) AS DLR_NM,
        $5::VARCHAR(55) AS RGNL_ZN_NM,
        $6::VARCHAR(55) AS DLR_ACNT_MGR_NM,
        $7::VARCHAR(55) AS DLR_GRP_NM,
        $8::NUMBER(12,2) AS CNTRCT_TRGT_NB,
        $9::NUMBER(12,2) AS RTL_CNTRCT_NB,
        $10::NUMBER(12,2) AS RTL_SL_NMEX_NB,
        $11::NUMBER(12,2) AS SELECTIVITY_LEASING_NB,
        $12::NUMBER(12,6) AS EXTND_WRNTY_PC,
        $13::STRING AS HASHKEY,
        $14::TIMESTAMP AS AUDIT_LOADED_DATE
    FROM '@NMEX_MAP_EXT_STG/validated/NRFM/nrfm'
) FILE_FORMAT = (
    TYPE = 'CSV',
    FIELD_DELIMITER = ';',
    SKIP_HEADER = 1,
    DATE_FORMAT = 'AUTO',
    TIMESTAMP_FORMAT = 'AUTO',
    NULL_IF = ('NULL', '','NaN','nan','NAN'),
    TRIM_SPACE = TRUE
) ON_ERROR = 'CONTINUE';