-- SnowPipe para CDO_DESGLOSE_TOTAL
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.CDO_DESGLOSE_TOTAL_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.CDO_DESGLOSE_TOTAL
FROM @NMEX_MAP_STG/CDO/CDO_DESGLOSE_TOTAL
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para CDO_REPROCESO
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.CDO_REPROCESO_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.CDO_REPROCESO
FROM @NMEX_MAP_STG/CDO/CDO_REPROCESO
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_AVG_ORS_MENSUAL
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_AVG_ORS_MENSUAL_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_AVG_ORS_MENSUAL
FROM @NMEX_MAP_STG/ICON/ICON_AVG_ORS_MENSUAL
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_AVG_VENTAS_MENSUAL
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_AVG_VENTAS_MENSUAL_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_AVG_VENTAS_MENSUAL
FROM @NMEX_MAP_STG/ICON/ICON_AVG_VENTAS_MENSUAL
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_DEALERS
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_DEALERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_DEALERS
FROM @NMEX_MAP_STG/ICON/ICON_DEALERS
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_OBJ_VENTAS_NIC
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_OBJ_VENTAS_NIC_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_OBJ_VENTAS_NIC
FROM @NMEX_MAP_STG/ICON/ICON_OBJ_VENTAS_NIC
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_OPORTUNIDADES_BDC_POSVENTA
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_OPORTUNIDADES_BDC_POSVENTA_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_OPORTUNIDADES_BDC_POSVENTA
FROM @NMEX_MAP_STG/ICON/ICON_OPORTUNIDADES_BDC_POSVENTA
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_REGLAS
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_REGLAS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_REGLAS
FROM @NMEX_MAP_STG/ICON/ICON_REGLAS
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para CDO_DESGLOSE_TOTAL
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.CDO_DESGLOSE_TOTAL_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.CDO_DESGLOSE_TOTAL
FROM @NMEX_MAP_STG/CDO/CDO_DESGLOSE_TOTAL
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para CDO_REPROCESO
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.CDO_REPROCESO_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.CDO_REPROCESO
FROM @NMEX_MAP_STG/CDO/CDO_REPROCESO
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_AVG_ORS_MENSUAL
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_AVG_ORS_MENSUAL_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_AVG_ORS_MENSUAL
FROM @NMEX_MAP_STG/ICON/ICON_AVG_ORS_MENSUAL
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_AVG_VENTAS_MENSUAL
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_AVG_VENTAS_MENSUAL_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_AVG_VENTAS_MENSUAL
FROM @NMEX_MAP_STG/ICON/ICON_AVG_VENTAS_MENSUAL
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_DEALERS
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_DEALERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_DEALERS
FROM @NMEX_MAP_STG/ICON/ICON_DEALERS
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_OBJ_VENTAS_NIC
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_OBJ_VENTAS_NIC_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_OBJ_VENTAS_NIC
FROM @NMEX_MAP_STG/ICON/ICON_OBJ_VENTAS_NIC
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_OPORTUNIDADES_BDC_POSVENTA
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_OPORTUNIDADES_BDC_POSVENTA_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_OPORTUNIDADES_BDC_POSVENTA
FROM @NMEX_MAP_STG/ICON/ICON_OPORTUNIDADES_BDC_POSVENTA
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para ICON_REGLAS
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.ICON_REGLAS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.ICON_REGLAS
FROM @NMEX_MAP_STG/ICON/ICON_REGLAS
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para JDP_SERVICIO_1M
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.JDP_SERVICIO_1M_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.JDP_SERVICIO_1M
FROM @NMEX_MAP_STG/JDP/JDP_SERVICIO_1M
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para JDP_SERVICIO_3M
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.JDP_SERVICIO_3M_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.JDP_SERVICIO_3M
FROM @NMEX_MAP_STG/JDP/JDP_SERVICIO_3M
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para JDP_VENTA_1M
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.JDP_VENTA_1M_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.JDP_VENTA_1M
FROM @NMEX_MAP_STG/JDP/JDP_VENTA_1M
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para JDP_VENTA_3M
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.JDP_VENTA_3M_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.JDP_VENTA_3M
FROM @NMEX_MAP_STG/JDP/JDP_VENTA_3M
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para NRFM
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.NRFM_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.NRFM
FROM @NMEX_MAP_STG/NRFM/NRFM
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';

-- SnowPipe para DLR_SYMMETRICAL
CREATE OR REPLACE PIPE SDDBMTS1.NMX_MTS1_STG.DLR_SYMMETRICAL_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO SDDBMTS1.NMX_MTS1_STG.DLR_SYMMETRICAL
FROM @NMEX_MAP_STG/DLR/DLR_SYMMETRICAL
FILE_FORMAT = (FORMAT_NAME = csvformat)
ON_ERROR = 'CONTINUE';
