-- Tabla: RSLT_SVC_NSN_EXPRNC_INDX_SG
CREATE OR REPLACE TABLE NMX_MTS1_STG.RSLT_SVC_NSN_EXPRNC_INDX_SG (
    FSCL_YR_NB NUMBER COMMENT 'Fiscal Year Number',
    FSCL_QTR_SHRT_NM NUMBER COMMENT 'Fiscal Quarter Short Name',
    DLR_CD VARCHAR(55) COMMENT 'Natural code that identifies dealer',
    DLR_NM VARCHAR(150) COMMENT 'Dealers Name',
    DLR_GRP_NM VARCHAR(55) COMMENT 'the name that identifies each group',
    DLR_ZN_NM VARCHAR(55) COMMENT 'sales area by region',
    RSLT_SVC_NB NUMBER(12,2) COMMENT 'Corresponds to the Service Result.',
    BDC_AFTSLS_OPRTNY_3_1_1_2_FLW_UP_NO_SHOW_NB NUMBER(12,2) COMMENT 'Corresponds to the activity of Follow-up on No Shows and pending work.',
    BDC_AFTSLS_CNTCT_3_1_2_1_CSTMR_INFRMN_NB NUMBER(12,2) COMMENT 'Corresponds to having all customer information available.',
    BDC_AFTSLS_CNTCT_3_1_2_2_FLW_GDLN_NB NUMBER(12,2) COMMENT 'Corresponds to following predetermined guidelines.',
    BDC_AFTSLS_APNTMT_3_1_3_1_PR_APNTMT_PREPARATION_NB NUMBER(12,2) COMMENT 'Corresponds to carrying out the necessary preparations before the appointment.',
    BDC_AFTSLS_APNTMT_3_1_3_2_RTNTN_CMPGN_NB NUMBER(12,2) COMMENT 'Corresponds to knowing the current retention campaigns.',
    BDC_AFTSLS_APNTMT_3_1_3_3_ENSURE_MNTNC_BNFT_NB NUMBER(12,2) COMMENT 'Corresponds to ensuring maintenance services and post-sale benefits.',
    BDC_AFTSLS_CNFMTN_3_1_4_1_CNFMTN_CALL_NB NUMBER(12,2) COMMENT 'Corresponds to ensuring that the appointment confirmation call is made.',
    BDC_AFTSLS_CNFMTN_3_1_4_2_PKUP_DLVRY_NB NUMBER(12,2) COMMENT 'Corresponds to the collection and home delivery appointment.',
    EFCTV_OPP_RCPTN_3_2_1_1_WLCM_CLNT_NB NUMBER(12,2) COMMENT 'Corresponds to welcoming the customer.',
    EFCTV_OPP_RCPTN_3_2_1_2_VHCL_ISPCTN_NB NUMBER(12,2) COMMENT 'Corresponds to the vehicle inspection and placement of protective covers.',
    EFCTV_OPP_RCPTN_3_2_1_3_LISTEN_CLNT_NEED_NB NUMBER(12,2) COMMENT 'Corresponds to listening to the customers needs.',
    EFCTV_OPP_QLTY_CMPGN_3_2_2_1_APLY_CMPGN_NB NUMBER(12,2) COMMENT 'Corresponds to the application of quality campaigns.',
    EFCTV_OPP_WRK_EXPLTN_3_2_3_1_EXPLAIN_TSK_NB NUMBER(12,2) COMMENT 'Corresponds to explaining the work to be performed.',
    EFCTV_OPP_WRK_EXPLTN_3_2_3_2_DLVRY_PRMSE_NB NUMBER(12,2) COMMENT 'Corresponds to providing the promised delivery time.',
    SVC_WRK_PRGRS_CTRL_3_3_1_2_MNTR_PRGRS_NB NUMBER(12,2) COMMENT 'Corresponds to monitoring the progress of the work.',
    SVC_WRKSHOP_3_3_2_1_WRK_TM_CLNT_CNTCT_NB NUMBER(12,2) COMMENT 'Corresponds to tracking the current work time and maintaining effective customer contact.',
    SVC_WRKSHOP_3_3_2_2_TOOL_IVNTRY_NB NUMBER(12,2) COMMENT 'Corresponds to the inventory of tools.',
    SVC_WRKSHOP_3_3_2_3_TOOL_MNTNC_NB NUMBER(12,2) COMMENT 'Corresponds to the maintenance of tools.',
    SVC_WRKSHOP_3_3_2_4_TOOL_EQPMNT_NB NUMBER(12,2) COMMENT 'Corresponds to tools and equipment.',
    SVC_WRKSHOP_3_3_2_5_MPI_NB NUMBER(12,2) COMMENT 'Corresponds to the multipoint inspection sheet.',
    SVC_NXT_APNTMT_3_3_3_1_SCHDL_NXT_SVC_NB NUMBER(12,2) COMMENT 'Corresponds to scheduling the next services.',
    WASH_STNDRD_3_4_1_1_WASH_ARA_CNDTN_NB NUMBER(12,2) COMMENT 'Corresponds to the general conditions of the washing area.',
    WASH_STNDRD_3_4_1_2_HMN_RSRC_NB NUMBER(12,2) COMMENT 'Corresponds to ensuring sufficient human resources.',
    WASH_STNDRD_3_4_1_3_WASH_PRCS_STG_NB NUMBER(12,2) COMMENT 'Corresponds to the washing process stages.',
    WASH_STNDRD_3_4_1_4_QLTY_ISPCTN_NB NUMBER(12,2) COMMENT 'Corresponds to the quality inspection of the washing process.',
    QLTY_CTRL_ISPCTN_3_5_1_1_RSPBLY_NB NUMBER(12,2) COMMENT 'Corresponds to fulfilling quality control responsibilities and knowledge.',
    QLTY_CTRL_ISPCTN_3_5_1_2_PRCS_EXCTN_NB NUMBER(12,2) COMMENT 'Corresponds to carrying out the quality control process.',
    QLTY_CTRL_PRGRM_F1_3_5_2_1_SLTN_RCLM_NB NUMBER(12,2) COMMENT 'Corresponds to immediate resolution in the claim stages and application of the PDCA control process.',
    DLVRY_FLW_UP_3_6_1_1_PREP_FOR_DLVRY_NB NUMBER(12,2) COMMENT 'Corresponds to preparation for delivery.',
    DLVRY_FLW_UP_3_6_1_2_DLVRY_EXPLTN_NB NUMBER(12,2) COMMENT 'Corresponds to explanation at the time of delivery.',
    DLVRY_FLW_UP_3_6_1_3_ROAD_ASTNC_NB NUMBER(12,2) COMMENT 'Corresponds to roadside assistance.',
    DLVRY_FLW_UP_3_6_1_4_NXT_SVC_RMNDR_NB NUMBER(12,2) COMMENT 'Corresponds to reminders for upcoming services and pending work.',
    FLW_UP_3_6_2_1_VOC_NB NUMBER(12,2) COMMENT 'Corresponds to VoC.',
    FLW_UP_3_6_2_2_CMPLNT_TRCKNG_CAC_NB NUMBER(12,2) COMMENT 'Corresponds to follow-up on complaints (CAC).',
    EXPRS_SVC_APNTMT_3_7_1_1_OFR_CNFRM_FLW_UP_NB NUMBER(12,2) COMMENT 'Corresponds to offering the Express Service, confirming the customers appointment, and following up on appointments.',
    EXPRS_SVC_RCPTN_3_7_2_1_RGSTR_INSPCT_EXPLAIN_NB NUMBER(12,2) COMMENT 'Corresponds to registering, inspecting, and explaining the work to be performed upon vehicle arrival.',
    EXPRS_SVC_CNTL_3_7_3_1_ASGN_WRK_NB NUMBER(12,2) COMMENT 'Corresponds to assigning work and additional tasks.',
    EXPRS_SVC_CNTL_3_7_3_2_USE_RAMP_TOOL_NB NUMBER(12,2) COMMENT 'Corresponds to the use of the Express ramp and tools.',
    EXPRS_SVC_CMNCTN_3_7_4_1_WASHING_STF_QLTY_NB NUMBER(12,2) COMMENT 'Corresponds to ensuring the availability of adequate washing personnel and confirming washing quality.',
    EXPRS_SVC_ISPCTN_3_7_5_1_QLTY_CNTL_NB NUMBER(12,2) COMMENT 'Corresponds to quality control of Express Service work and monitoring indicators.',
    EXPRS_SVC_CMNCTN_3_7_6_1_USE_POP_MTRL_NB NUMBER(12,2) COMMENT 'Corresponds to the use of current POP materials.',
    NREDI_SVC_5S_3_8_1_1_MNTNC_SVC_ARA_NB NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping the service and spare parts area in optimal condition.',
    NREDI_SVC_5S_3_8_1_2_MNTNC_RCPTN_NB NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping the reception area and advisor modules in optimal condition.',
    NREDI_SVC_5S_3_8_1_3_MNTNC_WRKSHOP_NB NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping the service workshop in optimal condition.',
    NREDI_SVC_5S_3_8_1_4_MNTNC_FACADE_NB NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping the facade elements and exterior spaces in optimal condition.',
    NREDI_SVC_5S_3_8_2_1_SELF_EVLTN_NB NUMBER(12,2) COMMENT 'Corresponds to the evaluation and follow-up of 5S methodology.',
    ORGANIZATIONAL_STRCTR_3_9_1_1_SVC_ADVSR NUMBER(12,2) COMMENT 'Corresponds to the required service advisors.',
    ORGANIZATIONAL_STRCTR_3_9_1_2_SVC_TCHNCN NUMBER(12,2) COMMENT 'Corresponds to service technicians.',
    ORGANIZATIONAL_STRCTR_3_9_1_3_WSHR_NB NUMBER(12,2) COMMENT 'Corresponds to washers.',
    ORGANIZATIONAL_STRCTR_3_9_1_4_QLTY_CNTL_NB NUMBER(12,2) COMMENT 'Corresponds to quality control.',
    HASHKEY STRING COMMENT 'Corresponds to the unique identifier of the table.',
    AUDIT_LOADED_DATE TIMESTAMP COMMENT 'Corresponds to the date when the data was loaded into the system for auditing purposes.'
)
COMMENT = 'Contains results of the Nissan Experience Index for service performance.';

-- Tabla RSLT_SVC_NSN_EXPRNC_INDX_2_SG
CREATE OR REPLACE TABLE NMX_NMTS1.RSLT_SVC_NSN_EXPRNC_INDX_2_SG (
    RSLT_SVC_NSN_EXPRNC_INDX_KY STRING COMMENT 'Contains a unique identifier or key for dealer performance records.',
    CLNDR_FY_NB NUMBER COMMENT 'Corresponds to Calendar Fiscal Year Number',
    CLNDR_FSCL_QTR_SHRT_NM NUMBER COMMENT 'Corresponds to Calendar Quarter Short Name',
    DLR_KY NUMBER COMMENT 'A unique system generated numeric value that identifies a specific dealer dimension row. Business Rule: - The value cannot be used for business information purposes - The value is never modified after the data base row is inserted - It is recommended that a unique index on the natural keys be created',
    DLR_CD VARCHAR (4) COMMENT 'Natural code that identifies dealer',
    RSLT_SVC_NB NUMBER(12,2) COMMENT 'Corresponds to the Service Result.',
    BDC_AFTSLS_OPRTNY_3_1_1_2_FLW_UP_NO_SHOW_NB NUMBER(12,2) COMMENT 'Corresponds to the activity of Follow-up on No Shows and pending work.',
    BDC_AFTSLS_CNTCT_3_1_2_1_CSTMR_INFRMN_NB NUMBER(12,2) COMMENT 'Corresponds to having all customer information available.',
    BDC_AFTSLS_CNTCT_3_1_2_2_FLW_GDLN_NB NUMBER(12,2) COMMENT 'Corresponds to following predetermined guidelines.',
    BDC_AFTSLS_APNTMT_3_1_3_1_PR_APNTMT_PREPARATION_NB NUMBER(12,2) COMMENT 'Corresponds to carrying out the necessary preparations before the appointment.',
    BDC_AFTSLS_APNTMT_3_1_3_2_RTNTN_CMPGN_NB NUMBER(12,2) COMMENT 'Corresponds to knowing the current retention campaigns.',
    BDC_AFTSLS_APNTMT_3_1_3_3_ENSURE_MNTNC_BNFT_NB NUMBER(12,2) COMMENT 'Corresponds to ensuring maintenance services and post-sale benefits.',
    BDC_AFTSLS_CNFMTN_3_1_4_1_CNFMTN_CALL_NB NUMBER(12,2) COMMENT 'Corresponds to ensuring that the appointment confirmation call is made.',
    BDC_AFTSLS_CNFMTN_3_1_4_2_PKUP_DLVRY_NB NUMBER(12,2) COMMENT 'Corresponds to the collection and home delivery appointment.',
    EFCTV_OPP_RCPTN_3_2_1_1_WLCM_CLNT_NB NUMBER(12,2) COMMENT 'Corresponds to welcoming the customer.',
    EFCTV_OPP_RCPTN_3_2_1_2_VHCL_ISPCTN_NB NUMBER(12,2) COMMENT 'Corresponds to the vehicle inspection and placement of protective covers.',
    EFCTV_OPP_RCPTN_3_2_1_3_LISTEN_CLNT_NEED_NB NUMBER(12,2) COMMENT 'Corresponds to listening to the customers needs.',
    EFCTV_OPP_QLTY_CMPGN_3_2_2_1_APLY_CMPGN_NB NUMBER(12,2) COMMENT 'Corresponds to the application of quality campaigns.',
    EFCTV_OPP_WRK_EXPLTN_3_2_3_1_EXPLAIN_TSK_NB NUMBER(12,2) COMMENT 'Corresponds to explaining the work to be performed.',
    EFCTV_OPP_WRK_EXPLTN_3_2_3_2_DLVRY_PRMSE_NB NUMBER(12,2) COMMENT 'Corresponds to providing the promised delivery time.',
    SVC_WRK_PRGRS_CTRL_3_3_1_2_MNTR_PRGRS_NB NUMBER(12,2) COMMENT 'Corresponds to monitoring the progress of the work.',
    SVC_WRKSHOP_3_3_2_1_WRK_TM_CLNT_CNTCT_NB NUMBER(12,2) COMMENT 'Corresponds to tracking the current work time and maintaining effective customer contact.',
    SVC_WRKSHOP_3_3_2_2_TOOL_IVNTRY_NB NUMBER(12,2) COMMENT 'Corresponds to the inventory of tools.',
    SVC_WRKSHOP_3_3_2_3_TOOL_MNTNC_NB NUMBER(12,2) COMMENT 'Corresponds to the maintenance of tools.',
    SVC_WRKSHOP_3_3_2_4_TOOL_EQPMNT_NB NUMBER(12,2) COMMENT 'Corresponds to tools and equipment.',
    SVC_WRKSHOP_3_3_2_5_MPI_NB NUMBER(12,2) COMMENT 'Corresponds to the multipoint inspection sheet.',
    SVC_NXT_APNTMT_3_3_3_1_SCHDL_NXT_SVC_NB NUMBER(12,2) COMMENT 'Corresponds to scheduling the next services.',
    WASH_STNDRD_3_4_1_1_WASH_ARA_CNDTN_NB NUMBER(12,2) COMMENT 'Corresponds to the general conditions of the washing area.',
    WASH_STNDRD_3_4_1_2_HMN_RSRC_NB NUMBER(12,2) COMMENT 'Corresponds to ensuring sufficient human resources.',
    WASH_STNDRD_3_4_1_3_WASH_PRCS_STG_NB NUMBER(12,2) COMMENT 'Corresponds to the washing process stages.',
    WASH_STNDRD_3_4_1_4_QLTY_ISPCTN_NB NUMBER(12,2) COMMENT 'Corresponds to the quality inspection of the washing process.',
    QLTY_CTRL_ISPCTN_3_5_1_1_RSPBLY_NB NUMBER(12,2) COMMENT 'Corresponds to fulfilling quality control responsibilities and knowledge.',
    QLTY_CTRL_ISPCTN_3_5_1_2_PRCS_EXCTN_NB NUMBER(12,2) COMMENT 'Corresponds to carrying out the quality control process.',
    QLTY_CTRL_PRGRM_F1_3_5_2_1_SLTN_RCLM_NB NUMBER(12,2) COMMENT 'Corresponds to immediate resolution in the claim stages and application of the PDCA control process.',
    DLVRY_FLW_UP_3_6_1_1_PREP_FOR_DLVRY_NB NUMBER(12,2) COMMENT 'Corresponds to preparation for delivery.',
    DLVRY_FLW_UP_3_6_1_2_DLVRY_EXPLTN_NB NUMBER(12,2) COMMENT 'Corresponds to explanation at the time of delivery.',
    DLVRY_FLW_UP_3_6_1_3_ROAD_ASTNC_NB NUMBER(12,2) COMMENT 'Corresponds to roadside assistance.',
    DLVRY_FLW_UP_3_6_1_4_NXT_SVC_RMNDR_NB NUMBER(12,2) COMMENT 'Corresponds to reminders for upcoming services and pending work.',
    FLW_UP_3_6_2_1_VOC_NB NUMBER(12,2) COMMENT 'Corresponds to VoC.',
    FLW_UP_3_6_2_2_CMPLNT_TRCKNG_CAC_NB NUMBER(12,2) COMMENT 'Corresponds to follow-up on complaints (CAC).',
    EXPRS_SVC_APNTMT_3_7_1_1_OFR_CNFRM_FLW_UP_NB NUMBER(12,2) COMMENT 'Corresponds to offering the Express Service, confirming the customers appointment, and following up on appointments.',
    EXPRS_SVC_RCPTN_3_7_2_1_RGSTR_INSPCT_EXPLAIN_NB NUMBER(12,2) COMMENT 'Corresponds to registering, inspecting, and explaining the work to be performed upon vehicle arrival.',
    EXPRS_SVC_CNTL_3_7_3_1_ASGN_WRK_NB NUMBER(12,2) COMMENT 'Corresponds to assigning work and additional tasks.',
    EXPRS_SVC_CNTL_3_7_3_2_USE_RAMP_TOOL_NB NUMBER(12,2) COMMENT 'Corresponds to the use of the Express ramp and tools.',
    EXPRS_SVC_CMNCTN_3_7_4_1_WASHING_STF_QLTY_NB NUMBER(12,2) COMMENT 'Corresponds to ensuring the availability of adequate washing personnel and confirming washing quality.',
    EXPRS_SVC_ISPCTN_3_7_5_1_QLTY_CNTL_NB NUMBER(12,2) COMMENT 'Corresponds to quality control of Express Service work and monitoring indicators.',
    EXPRS_SVC_CMNCTN_3_7_6_1_USE_POP_MTRL_NB NUMBER(12,2) COMMENT 'Corresponds to the use of current POP materials.',
    NREDI_SVC_5S_3_8_1_1_MNTNC_SVC_ARA_NB NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping the service and spare parts area in optimal condition.',
    NREDI_SVC_5S_3_8_1_2_MNTNC_RCPTN_NB NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping the reception area and advisor modules in optimal condition.',
    NREDI_SVC_5S_3_8_1_3_MNTNC_WRKSHOP_NB NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping the service workshop in optimal condition.',
    NREDI_SVC_5S_3_8_1_4_MNTNC_FACADE_NB NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping the facade elements and exterior spaces in optimal condition.',
    NREDI_SVC_5S_3_8_2_1_SELF_EVLTN_NB NUMBER(12,2) COMMENT 'Corresponds to the evaluation and follow-up of 5S methodology.',
    ORGANIZATIONAL_STRCTR_3_9_1_1_SVC_ADVSR NUMBER(12,2) COMMENT 'Corresponds to the required service advisors.',
    ORGANIZATIONAL_STRCTR_3_9_1_2_SVC_TCHNCN NUMBER(12,2) COMMENT 'Corresponds to service technicians.',
    ORGANIZATIONAL_STRCTR_3_9_1_3_WSHR_NB NUMBER(12,2) COMMENT 'Corresponds to washers.',
    ORGANIZATIONAL_STRCTR_3_9_1_4_QLTY_CNTL_NB NUMBER(12,2) COMMENT 'Corresponds to quality control.',
    ADT_LOD_DT TIMESTAMP COMMENT 'Corresponds to the date when the data was loaded into the system for auditing purposes.',   
    CRTE_USR_ID VARCHAR(50) COMMENT 'Unique value of person, program module or service that initially created this row or record in this table. Business Rule: This field is used for audit purposes only The Create User Identifier cannot be used to represent business information The value is obtained from the security service The value is not directly manipulated by business users or applications This information remains unchanged for the entire life of the record.',
    UPDT_USR_ID VARCHAR(50) COMMENT 'Unique value of person, program module or service that modified this row or record in this table. Business Rule: The value is used for audit purposes only The value cannot be used for business information purposes The value is obtained from the security service The value is not directly manipulated by business users or applications. On insert into the database the value will be set to be the same as the Create User Identifier',
    CRTE_TS TIMESTAMP COMMENT 'Date and time when this row or record was inserted into this table.Business Rule: The value is used for audit purposes only The Create Timestamp cannot be used for business information purposes The information is automatically populated by the database when a row is inserted The date and time value cannot be modified by the application.',
    UPDT_TS TIMESTAMP COMMENT 'Date and time when this row or record was last updated or modified in this table.Business Rule: The value is used for audit purposes only The Update Timestamp cannot be used for business information purposes The information is automatically populated by the database when a row is updated The date and time value cannot be modified by the application On insert into the database the value will be set to be the same as the Create Timestamp.'
)
COMMENT = 'Contains results of the Nissan Experience Index for service performance.';

-- Tabla: RSLT_SLS_NSN_EXPRNC_INDX_SG
CREATE OR REPLACE TABLE NMX_MTS1_STG.RSLT_SLS_NSN_EXPRNC_INDX_SG (
    FSCL_YR_NB NUMBER COMMENT 'Fiscal Year Number',
    FSCL_QTR_SHRT_NM NUMBER COMMENT 'Fiscal Quarter Short Name',
    DLR_CD VARCHAR(55) COMMENT 'Natural code that identifies dealer',
    DLR_NM VARCHAR(150) COMMENT 'Dealers Name',
    DLR_GRP_NM VARCHAR(55) COMMENT 'the name that identifies each group',
    DLR_ZN_NM VARCHAR(55) COMMENT 'sales area by region',
    RSLT_SL_NB NUMBER(12,2) COMMENT 'Corresponds to Sales Result.',
    RSLT_SVC_NB NUMBER(12,2) COMMENT 'Corresponds to Service Result.',
    RSLT_EFCTVNS_NB NUMBER(12,2) COMMENT 'Corresponds to Effectiveness Result.',
    BSNS_DVLPMT_CTR_2_1_1_1_OPRTNY_MGMT NUMBER(12,2) COMMENT 'Corresponds to classifying sales opportunities from the four available sources according to NMEX-established categories.',
    BSNS_DVLPMT_CTR_2_1_2_1_CSTMR_INFRMN NUMBER(12,2) COMMENT 'Corresponds to having all customer information available.',
    BSNS_DVLPMT_CTR_2_1_3_1_APNTMT_PREPARATION NUMBER(12,2) COMMENT 'Corresponds to preparing the appointment.',
    BSNS_DVLPMT_CTR_2_1_4_1_APNTMT_CNFMTN NUMBER(12,2) COMMENT 'Corresponds to ensuring the appointment confirmation call is made.',
    EFCTV_OPRTNY_RCPTN_2_2_1_1_WLCM_CLNT_NB NUMBER(12,2) COMMENT 'Corresponds to welcoming the customer according to NMEX guidelines.',
    EFCTV_OPRTNY_2_2_1_2_CSTMR_RGSTRN NUMBER(12,2) COMMENT 'Corresponds to obtaining and recording customer data in CRM (Seekop).',
    EFCTV_OPRTNY_2_2_1_3_APV_ASGNMT NUMBER(12,2) COMMENT 'Corresponds to introducing the APV to the customer, considering the customers availability and preference for an APV.',
    EFCTV_OPRTNY_CNSLT_2_2_2_1_IDNTFY_NEED_NB NUMBER(12,2) COMMENT 'Corresponds to identifying customer needs to guide them toward the most suitable vehicle.',
    EFCTV_OPRTNY_2_2_2_2_HM_CNSLTON_TOOL NUMBER(12,2) COMMENT 'Corresponds to having the necessary tools to conduct an at-home consultation.',
    EFCTV_OPRTNY_CNSLT_2_2_2_3_TOOL_DGTL_NB NUMBER(12,2) COMMENT 'Corresponds to having the necessary tools to conduct a digital consultation.',
    PRDT_PRSNT_STC_2_3_1_1_EXPLAIN_FEATR_NB NUMBER(12,2) COMMENT 'Corresponds to explaining the vehicle and brand attributes using the different demonstration techniques provided by NMEX.',
    PRDT_PRSNT_STC_2_3_1_2_ACSR_NB NUMBER(12,2) COMMENT 'Corresponds to accessorizing and explaining the accessories included with the unit to the customer.',
    PRDT_PRSNT_STC_2_3_1_3_ACSRY_COMMS_NB NUMBER(12,2) COMMENT 'Corresponds to accessory communication.',
    PRDT_PRSNT_TST_DRV_2_3_2_1_CAR_AVLBTY_NB NUMBER(12,2) COMMENT 'Corresponds to verifying the availability and condition of demo vehicles.',
    PRDT_PRSNT_TST_DRV_2_3_2_2_LCNS_CK_NB NUMBER(12,2) COMMENT 'Corresponds to requesting a valid drivers license from the customer for the test drive.',
    PRDT_PRSNT_TST_DRV_2_3_2_3_EXPLAIN_FEATR_NB NUMBER(12,2) COMMENT 'Corresponds to explaining the qualities, virtues, and key aspects of the unit.',
    PRDT_PRSNT_TST_DRV_2_3_2_4_CLNT_AMENITIES_NB NUMBER(12,2) COMMENT 'Corresponds to offering amenities to the customer and ensuring all questions or concerns are addressed.',
    PRDT_PRSNT_TST_DRV_2_3_2_5_STSFCN_SRVY_NB NUMBER(12,2) COMMENT 'Corresponds to conducting a satisfaction survey for the test drive.',
    ECNMC_PRPSL_TRADIN_2_4_1_1_PROMOTE_PRGRM_NB NUMBER(12,2) COMMENT 'Corresponds to promoting customer vehicle trade-ins through the NIC Renueva program.',
    ECNMC_PRPSL_SL_CLSR_2_4_2_1_PRFL_NB NUMBER(12,2) COMMENT 'Corresponds to performing profiling activities to collect and verify customer data.',
    ECNMC_PRPSL_SL_CLSR_2_4_2_2_DOC_CKLIST_NB NUMBER(12,2) COMMENT 'Corresponds to providing the customer with a checklist of required documents for the credit application process.',
    ECNMC_PRPSL_2_4_2_4_SLS_CLSR_STRTGY NUMBER(12,2) COMMENT 'Corresponds to knowing and employing verbal and non-verbal strategies, as well as closing techniques, to assist the customer in making a decision.',
    ECNMC_PRPSL_SL_CLSR_2_4_2_5_CRDT_APP_NB NUMBER(12,2) COMMENT 'Corresponds to completing the credit application form.',
    DLVRY_FLW_UP_2_5_1_1_PREP_SCHDL_NB NUMBER(12,2) COMMENT 'Corresponds to preparing and scheduling the units delivery.',
    DLVRY_FLW_UP_2_5_1_2_CNFRM_CLNT_DTLS_NB NUMBER(12,2) COMMENT 'Corresponds to confirming with the customer key details regarding vehicle delivery.',
    DLVRY_FLW_UP_2_5_1_3_PREP_VHCL_NB NUMBER(12,2) COMMENT 'Corresponds to preparing the vehicle for delivery.',
    DLVRY_FLW_UP_2_5_1_4_RCV_CLNT_NB NUMBER(12,2) COMMENT 'Corresponds to warmly receiving the customer and their companions.',
    DLVRY_FLW_UP_2_5_1_5_HNDVR_DOCS_VHCL_NB NUMBER(12,2) COMMENT 'Corresponds to delivering the documentation and vehicle to the customer.',
    FLW_UP_2_5_2_1_SLSFRC_CMPLNT_NB NUMBER(12,2) COMMENT 'Corresponds to identifying post-sale complaints via Salesforce, providing solutions, and creating a follow-up analysis.',
    GTE_4_2_6_1_1_NEW_VHCL_RCPT NUMBER(12,2) COMMENT 'Corresponds to vehicle reception.',
    GTE_4_2_6_1_2_STRG_CNDTN NUMBER(12,2) COMMENT 'Corresponds to warehouse conditions and storage.',
    GTE_4_2_6_1_3_PRDCTY_MNTNC NUMBER(12,2) COMMENT 'Corresponds to periodic maintenance of the units.',
    GTE_4_2_6_1_4_ACSRY_INSTLN NUMBER(12,2) COMMENT 'Corresponds to accessory installation.',
    GTE_4_2_6_1_5_PR_DLVRY_ISPCTN NUMBER(12,2) COMMENT 'Corresponds to PDI (Pre-Delivery Inspection) service.',
    GTE_4_2_6_1_6_CSTMR_DLVRY_SHWRM NUMBER(12,2) COMMENT 'Corresponds to customer delivery and showroom.',
    GTE_4_2_6_1_7_QLTY_MGMT_SYSTM NUMBER(12,2) COMMENT 'Corresponds to the quality management system.',
    NREDI_SLS_AND_5S_2_7_1_1_SHWRM_MNTNC NUMBER(12,2) COMMENT 'Corresponds to maintaining the vehicle exhibition area.',
    NREDI_SLS_AND_5S_2_7_1_2_CNSLTON_ARA_MNTNC NUMBER(12,2) COMMENT 'Corresponds to maintaining the consultation areas.',
    NREDI_SLS_AND_5S_2_7_1_3_VHCL_DLVRY_ARA_MNTNC NUMBER(12,2) COMMENT 'Corresponds to maintaining the vehicle delivery area.',
    NREDI_SLS_AND_5S_2_7_1_4_FACADE_AND_OUTDOR_SPC_MNTNC NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping facade elements and exterior spaces in optimal condition.',
    NREDI_SLS_AND_5S_2_7_2_1_SELF_EVLTN_AND_FLW_UP NUMBER(12,2) COMMENT 'Corresponds to the evaluation and follow-up of the 5S methodology.',
    NREDI_SLS_AND_5S_2_8_1_1_RQRD_SLS_ADVSR NUMBER(12,2) COMMENT 'Corresponds to required sales advisors.',
    NREDI_SLS_AND_5S_2_8_1_2_RQRD_BM_SLS NUMBER(12,2) COMMENT 'Corresponds to required BM sales representatives.',
    NREDI_SLS_AND_5S_2_8_1_3_SLS_STRCTR NUMBER(12,2) COMMENT 'Corresponds to sales structure.',
    NREDI_SLS_AND_5S_2_8_1_4_ADPC NUMBER(12,2) COMMENT 'Corresponds to ADPC.',
    HASHKEY STRING COMMENT 'Corresponds to the unique identifier of the table.',
    AUDIT_LOADED_DATE TIMESTAMP COMMENT 'Corresponds to the date when the data was loaded into the system for auditing purposes.'
)
COMMENT = 'Contains results of the Nissan Experience Index for sales performance.';

-- Tabla RSLT_SLS_NSN_EXPRNC_INDX_2_SG
CREATE OR REPLACE TABLE NMX_NMTS1.RSLT_SLS_NSN_EXPRNC_INDX_2_SG (
    RSLT_SLS_NSN_EXPRNC_INDX_KY STRING COMMENT 'Contains a unique identifier or key for dealer performance records.',
    CLNDR_FY_NB NUMBER COMMENT 'Corresponds to Calendar Fiscal Year Number',
    CLNDR_FSCL_QTR_SHRT_NM NUMBER COMMENT 'Corresponds to Calendar Quarter Short Name',
    DLR_KY NUMBER COMMENT 'A unique system generated numeric value that identifies a specific dealer dimension row. Business Rule: - The value cannot be used for business information purposes - The value is never modified after the data base row is inserted - It is recommended that a unique index on the natural keys be created',
    DLR_CD VARCHAR (4) COMMENT 'Natural code that identifies dealer',
    RSLT_SL_NB NUMBER(12,2) COMMENT 'Corresponds to Sales Result.',
    RSLT_SVC_NB NUMBER(12,2) COMMENT 'Corresponds to Service Result.',
    RSLT_EFCTVNS_NB NUMBER(12,2) COMMENT 'Corresponds to Effectiveness Result.',
    BSNS_DVLPMT_CTR_2_1_1_1_OPRTNY_MGMT NUMBER(12,2) COMMENT 'Corresponds to classifying sales opportunities from the four available sources according to NMEX-established categories.',
    BSNS_DVLPMT_CTR_2_1_2_1_CSTMR_INFRMN NUMBER(12,2) COMMENT 'Corresponds to having all customer information available.',
    BSNS_DVLPMT_CTR_2_1_3_1_APNTMT_PREPARATION NUMBER(12,2) COMMENT 'Corresponds to preparing the appointment.',
    BSNS_DVLPMT_CTR_2_1_4_1_APNTMT_CNFMTN NUMBER(12,2) COMMENT 'Corresponds to ensuring the appointment confirmation call is made.',
    EFCTV_OPRTNY_RCPTN_2_2_1_1_WLCM_CLNT_NB NUMBER(12,2) COMMENT 'Corresponds to welcoming the customer according to NMEX guidelines.',
    EFCTV_OPRTNY_2_2_1_2_CSTMR_RGSTRN NUMBER(12,2) COMMENT 'Corresponds to obtaining and recording customer data in CRM (Seekop).',
    EFCTV_OPRTNY_2_2_1_3_APV_ASGNMT NUMBER(12,2) COMMENT 'Corresponds to introducing the APV to the customer, considering the customers availability and preference for an APV.',
    EFCTV_OPRTNY_CNSLT_2_2_2_1_IDNTFY_NEED_NB NUMBER(12,2) COMMENT 'Corresponds to identifying customer needs to guide them toward the most suitable vehicle.',
    EFCTV_OPRTNY_2_2_2_2_HM_CNSLTON_TOOL NUMBER(12,2) COMMENT 'Corresponds to having the necessary tools to conduct an at-home consultation.',
    EFCTV_OPRTNY_CNSLT_2_2_2_3_TOOL_DGTL_NB NUMBER(12,2) COMMENT 'Corresponds to having the necessary tools to conduct a digital consultation.',
    PRDT_PRSNT_STC_2_3_1_1_EXPLAIN_FEATR_NB NUMBER(12,2) COMMENT 'Corresponds to explaining the vehicle and brand attributes using the different demonstration techniques provided by NMEX.',
    PRDT_PRSNT_STC_2_3_1_2_ACSR_NB NUMBER(12,2) COMMENT 'Corresponds to accessorizing and explaining the accessories included with the unit to the customer.',
    PRDT_PRSNT_STC_2_3_1_3_ACSRY_COMMS_NB NUMBER(12,2) COMMENT 'Corresponds to accessory communication.',
    PRDT_PRSNT_TST_DRV_2_3_2_1_CAR_AVLBTY_NB NUMBER(12,2) COMMENT 'Corresponds to verifying the availability and condition of demo vehicles.',
    PRDT_PRSNT_TST_DRV_2_3_2_2_LCNS_CK_NB NUMBER(12,2) COMMENT 'Corresponds to requesting a valid drivers license from the customer for the test drive.',
    PRDT_PRSNT_TST_DRV_2_3_2_3_EXPLAIN_FEATR_NB NUMBER(12,2) COMMENT 'Corresponds to explaining the qualities, virtues, and key aspects of the unit.',
    PRDT_PRSNT_TST_DRV_2_3_2_4_CLNT_AMENITIES_NB NUMBER(12,2) COMMENT 'Corresponds to offering amenities to the customer and ensuring all questions or concerns are addressed.',
    PRDT_PRSNT_TST_DRV_2_3_2_5_STSFCN_SRVY_NB NUMBER(12,2) COMMENT 'Corresponds to conducting a satisfaction survey for the test drive.',
    ECNMC_PRPSL_TRADIN_2_4_1_1_PROMOTE_PRGRM_NB NUMBER(12,2) COMMENT 'Corresponds to promoting customer vehicle trade-ins through the NIC Renueva program.',
    ECNMC_PRPSL_SL_CLSR_2_4_2_1_PRFL_NB NUMBER(12,2) COMMENT 'Corresponds to performing profiling activities to collect and verify customer data.',
    ECNMC_PRPSL_SL_CLSR_2_4_2_2_DOC_CKLIST_NB NUMBER(12,2) COMMENT 'Corresponds to providing the customer with a checklist of required documents for the credit application process.',
    ECNMC_PRPSL_2_4_2_4_SLS_CLSR_STRTGY NUMBER(12,2) COMMENT 'Corresponds to knowing and employing verbal and non-verbal strategies, as well as closing techniques, to assist the customer in making a decision.',
    ECNMC_PRPSL_SL_CLSR_2_4_2_5_CRDT_APP_NB NUMBER(12,2) COMMENT 'Corresponds to completing the credit application form.',
    DLVRY_FLW_UP_2_5_1_1_PREP_SCHDL_NB NUMBER(12,2) COMMENT 'Corresponds to preparing and scheduling the units delivery.',
    DLVRY_FLW_UP_2_5_1_2_CNFRM_CLNT_DTLS_NB NUMBER(12,2) COMMENT 'Corresponds to confirming with the customer key details regarding vehicle delivery.',
    DLVRY_FLW_UP_2_5_1_3_PREP_VHCL_NB NUMBER(12,2) COMMENT 'Corresponds to preparing the vehicle for delivery.',
    DLVRY_FLW_UP_2_5_1_4_RCV_CLNT_NB NUMBER(12,2) COMMENT 'Corresponds to warmly receiving the customer and their companions.',
    DLVRY_FLW_UP_2_5_1_5_HNDVR_DOCS_VHCL_NB NUMBER(12,2) COMMENT 'Corresponds to delivering the documentation and vehicle to the customer.',
    FLW_UP_2_5_2_1_SLSFRC_CMPLNT_NB NUMBER(12,2) COMMENT 'Corresponds to identifying post-sale complaints via Salesforce, providing solutions, and creating a follow-up analysis.',
    GTE_4_2_6_1_1_NEW_VHCL_RCPT NUMBER(12,2) COMMENT 'Corresponds to vehicle reception.',
    GTE_4_2_6_1_2_STRG_CNDTN NUMBER(12,2) COMMENT 'Corresponds to warehouse conditions and storage.',
    GTE_4_2_6_1_3_PRDCTY_MNTNC NUMBER(12,2) COMMENT 'Corresponds to periodic maintenance of the units.',
    GTE_4_2_6_1_4_ACSRY_INSTLN NUMBER(12,2) COMMENT 'Corresponds to accessory installation.',
    GTE_4_2_6_1_5_PR_DLVRY_ISPCTN NUMBER(12,2) COMMENT 'Corresponds to PDI (Pre-Delivery Inspection) service.',
    GTE_4_2_6_1_6_CSTMR_DLVRY_SHWRM NUMBER(12,2) COMMENT 'Corresponds to customer delivery and showroom.',
    GTE_4_2_6_1_7_QLTY_MGMT_SYSTM NUMBER(12,2) COMMENT 'Corresponds to the quality management system.',
    NREDI_SLS_AND_5S_2_7_1_1_SHWRM_MNTNC NUMBER(12,2) COMMENT 'Corresponds to maintaining the vehicle exhibition area.',
    NREDI_SLS_AND_5S_2_7_1_2_CNSLTON_ARA_MNTNC NUMBER(12,2) COMMENT 'Corresponds to maintaining the consultation areas.',
    NREDI_SLS_AND_5S_2_7_1_3_VHCL_DLVRY_ARA_MNTNC NUMBER(12,2) COMMENT 'Corresponds to maintaining the vehicle delivery area.',
    NREDI_SLS_AND_5S_2_7_1_4_FACADE_AND_OUTDOR_SPC_MNTNC NUMBER(12,2) COMMENT 'Corresponds to maintaining and keeping facade elements and exterior spaces in optimal condition.',
    NREDI_SLS_AND_5S_2_7_2_1_SELF_EVLTN_AND_FLW_UP NUMBER(12,2) COMMENT 'Corresponds to the evaluation and follow-up of the 5S methodology.',
    NREDI_SLS_AND_5S_2_8_1_1_RQRD_SLS_ADVSR NUMBER(12,2) COMMENT 'Corresponds to required sales advisors.',
    NREDI_SLS_AND_5S_2_8_1_2_RQRD_BM_SLS NUMBER(12,2) COMMENT 'Corresponds to required BM sales representatives.',
    NREDI_SLS_AND_5S_2_8_1_3_SLS_STRCTR NUMBER(12,2) COMMENT 'Corresponds to sales structure.',
    NREDI_SLS_AND_5S_2_8_1_4_ADPC NUMBER(12,2) COMMENT 'Corresponds to ADPC.',
    ADT_LOD_DT TIMESTAMP COMMENT 'Corresponds to the date when the data was loaded into the system for auditing purposes.',   
    CRTE_USR_ID VARCHAR(50) COMMENT 'Unique value of person, program module or service that initially created this row or record in this table. Business Rule: This field is used for audit purposes only The Create User Identifier cannot be used to represent business information The value is obtained from the security service The value is not directly manipulated by business users or applications This information remains unchanged for the entire life of the record.',
    UPDT_USR_ID VARCHAR(50) COMMENT 'Unique value of person, program module or service that modified this row or record in this table. Business Rule: The value is used for audit purposes only The value cannot be used for business information purposes The value is obtained from the security service The value is not directly manipulated by business users or applications. On insert into the database the value will be set to be the same as the Create User Identifier',
    CRTE_TS TIMESTAMP COMMENT 'Date and time when this row or record was inserted into this table.Business Rule: The value is used for audit purposes only The Create Timestamp cannot be used for business information purposes The information is automatically populated by the database when a row is inserted The date and time value cannot be modified by the application.',
    UPDT_TS TIMESTAMP COMMENT 'Date and time when this row or record was last updated or modified in this table.Business Rule: The value is used for audit purposes only The Update Timestamp cannot be used for business information purposes The information is automatically populated by the database when a row is updated The date and time value cannot be modified by the application On insert into the database the value will be set to be the same as the Create Timestamp.'
)
COMMENT = 'Contains results of the Nissan Experience Index for sales performance.';