CREATE OR REPLACE TABLE ICON_REGLAS (
    NEW_POSITION VARCHAR(150) AS NEW_PSTN_DS,
    POSITION_TYPE VARCHAR(50) AS PSTN_TYP_DS,
    STORE_SIZE VARCHAR(50) AS STOR_SIZE_DS,
    MINIMUM_REQUIRED_STAFF NUMBER AS MNM_RQRD_STF_NB,
    HashKey STRING,              -- Added column for unique row identifier or hash
    audit_loaded_date TIMESTAMP  -- Added column for tracking when the row was loaded
);

GRANT SELECT, INSERT, UPDATE, REFERENCES ON SDDBMTS1.NMX_MTS1_STG.ICON_REGLAS TO ROLE "ENTER ROLE"_$(ENV);